language: rust
rust:
  - stable
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo build --no-default-features --all --verbose
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt -- --check
os:
  - linux
  - osx
  - windows
