[package]
name = "doh-client"
version = "1.4.4"
authors = ["link.ted@mailbox.org"]
license = "BSD-3-Clause"
description = "DNS over HTTPS client"
readme = "README.md"
keywords = ["doh", "dns", "http2", "h2"]
exclude = [
    ".travis.yml",
    ".gitignore",
    "com.doh-client.daemon.plist",
    "doh-client.service",
    "doh-client.socket",
    "usr.local.bin.doh-client"
    ]
repository = "https://github.com/LinkTed/doh-client"
categories = [
    "command-line-utilities",
    "network-programming"
    ]

[badges]
travis-ci = { repository = "LinkTed/doh-client" }

[dependencies]
libc = "0.2.60"
data-encoding = "2.1.2"
log = "0.4.8"
clap = "2.33.0"
tokio = "0.1.22"
tokio-rustls = "0.10.0"
futures = "0.1.28"
futures-locks = "0.3.3"
h2 = "0.1.26"
http = "0.1.18"
rustls = "0.16.0"
webpki = "0.21.0"
bytes = "0.4.12"
lru = "0.1.16"
