[package]
name = "doh-client"
version = "1.4.5"
edition = "2018"
authors = ["LinkTed <link.ted@mailbox.org>"] 
license = "BSD-3-Clause"
description = "DNS over HTTPS client"
readme = "README.md"
keywords = ["doh", "dns", "http2", "h2"]
exclude = [
    ".travis.yml",
    ".gitignore",
    "com.doh-client.daemon.plist",
    "doh-client.service",
    "doh-client.socket",
    "usr.local.bin.doh-client"
    ]
repository = "https://github.com/LinkTed/doh-client"
categories = [
    "command-line-utilities",
    "network-programming"
    ]

[badges]
travis-ci = { repository = "LinkTed/doh-client" }

[dependencies]
libc = "0.2.65"
data-encoding = "2.1.2"
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
tokio = "0.2.0-alpha.6"
tokio-net = "0.2.0-alpha.6"
tokio-rustls = "0.12.0-alpha.5"
futures-preview = "0.3.0-alpha.19"
h2 = "0.2.0-alpha.3"
http = "0.1.19"
rustls = "0.16.0"
webpki = "0.21.0"
bytes = "0.4.12"
lru = "0.4.0"

[[bin]]
name = "completions"
path = "src/main_completions.rs"
