[package]
name = "doh-client"
version = "2.0.0"
edition = "2018"
authors = ["LinkTed <link.ted@mailbox.org>"] 
license = "BSD-3-Clause"
description = "DNS over HTTPS client"
readme = "README.md"
keywords = ["doh", "dns", "http2", "h2"]
exclude = [
    ".travis.yml",
    ".gitignore",
    "com.doh-client.daemon.plist",
    "doh-client.service",
    "doh-client.socket",
    "usr.bin.doh-client"
    ]
repository = "https://github.com/LinkTed/doh-client"
categories = [
    "command-line-utilities",
    "network-programming"
    ]

[badges]
travis-ci = { repository = "LinkTed/doh-client" }

[dependencies]
libc = "0.2.66"
data-encoding = "2.1.2"
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
tokio-rustls = "0.12.1"
futures = "0.3.1"
h2 = "0.2.0"
http = "0.2.0" 
rustls = "0.16.0"
webpki = "0.21.0"
bytes = "0.5.3"
lru = "0.4.3"

[dependencies.tokio]
version = "0.2.5"
features = ["rt-core", "net", "time", "macros"]

[dependencies.tokio-util]
version = "0.2.0"
features = ["codec", "udp"]

[[bin]]
name = "completions"
path = "src/main_completions.rs"

[profile.release]
lto = true
codegen-units = 1
