[package]
name = "doh-client"
version = "1.1.3"
authors = ["link.ted@mailbox.org"]
license = "BSD-3-Clause"
description = "DNS over HTTPS client"
readme = "README.md"
keywords = ["doh","dns", "http2", "h2"]
exclude = [
    ".gitignore",
    "com.doh-client.daemon.plist",
    "doh-client.service",
    "doh-client.socket",
    ]
repository = "https://github.com/LinkTed/doh-client"
categories = [
    "command-line-utilities",
    "network-programming"
    ]

[dependencies]
libc = "0.2.45"
log = "0.4.6"
clap = "2.32.0"
tokio = "0.1.13"
tokio-rustls = "0.8.0"
futures = "0.1.25"
futures-locks = "0.3.0"
h2 = "0.1.14"
http = "0.1.14"
rustls = "0.14.0"
webpki = "0.18.1"
bytes = "0.4.11"

