[package]
name = "doh-client"
version = "1.3.5"
authors = ["link.ted@mailbox.org"]
license = "BSD-3-Clause"
description = "DNS over HTTPS client"
readme = "README.md"
keywords = ["doh", "dns", "http2", "h2"]
exclude = [
    ".travis.yml",
    ".gitignore",
    "com.doh-client.daemon.plist",
    "doh-client.service",
    "doh-client.socket",
    "usr.local.bin.doh-client"
    ]
repository = "https://github.com/LinkTed/doh-client"
categories = [
    "command-line-utilities",
    "network-programming"
    ]

[badges]
travis-ci = { repository = "LinkTed/doh-client" }

[dependencies]
libc = "0.2.48"
data-encoding = "2.1.2"
log = "0.4.6"
clap = "2.32.0"
tokio = "0.1.15"
tokio-rustls = "0.9.0"
futures = "0.1.25"
futures-locks = "0.3.1"
h2 = "0.1.16"
http = "0.1.15"
rustls = "0.15.0"
webpki = "0.19.1"
bytes = "0.4.11"
